import { StyleSheet } from '@react-pdf/renderer';
import { colors, LAYOUT } from './planner-document-constants';

export const styles = StyleSheet.create({
  page: {
    padding: LAYOUT.pagePadding,
    fontFamily: 'Roboto',
    fontSize: 9,
    color: colors.black,
    backgroundColor: colors.white,
  },
  pageContent: { flex: 1, flexDirection: 'column' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: LAYOUT.headerHeight,
    marginBottom: LAYOUT.headerMargin,
    paddingBottom: 4,
    borderBottomWidth: 0.75,
    borderBottomColor: colors.darkGray,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  appName: { fontSize: 12, fontWeight: 700, color: colors.black },
  weekInfo: { fontSize: 10, fontWeight: 400, color: colors.darkGray },
  qrContainer: { width: 24, height: 24 },
  qrImage: { width: 24, height: 24 },
  dayRow: {
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGray,
    paddingTop: 4,
    paddingBottom: 3,
  },
  dayRowLast: { paddingTop: 4, paddingBottom: 3 },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
    paddingLeft: 5,
    borderLeftWidth: 2,
    borderLeftColor: colors.darkGray,
  },
  dayName: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.black,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dayDate: { fontSize: 9, color: colors.mediumGray, marginLeft: 8 },
  dayContent: { flex: 1, paddingLeft: 8 },
  subjectSection: { marginBottom: 2 },
  subjectLabel: {
    fontSize: 8,
    fontWeight: 500,
    color: colors.darkGray,
    marginBottom: 1,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: LAYOUT.lineHeight,
  },
  bullet: { fontSize: 8, color: colors.mediumGray, marginRight: 4, width: 8 },
  writingLine: {
    flex: 1,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.veryLightGray,
    height: LAYOUT.lineHeight - 2,
  },
  emptyDay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 6,
  },
  emptyDayText: { fontSize: 8, color: colors.lightGray, fontStyle: 'italic' },
  notesSection: { paddingTop: 4, paddingBottom: 3 },
  notesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
    paddingLeft: 5,
    borderLeftWidth: 2,
    borderLeftColor: colors.darkGray,
  },
  notesTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.black,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  notesContent: { flex: 1, paddingLeft: 8 },
});
