apps:
    web:
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:FS2XkBSFhWaODzUlob+bdVGYyqQN7dTSVxRcFEEnhyMeSu3rIKvKR3VKb62/3CtxmPFGajejsycQnQptgYtumQ==,iv:QjNOgPdi+DEYdDikto4lAmbNDR23hlVo2mjWX5Zno8Y=,tag:OzswuicqfHPyIHYLkN9HLQ==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:kyc1MjfuJpoWhsWD+RxBrCB2rceVLe15ighWpJeExMTb,iv:c+lhjTqkWGKUWi8/M5FXSBFNLz+8ZUvGrI72ggblx28=,tag:9Hlms2FzAbU1g9n2s6f/yA==,type:str]
        DATABASE_URL: ENC[AES256_GCM,data:RzklgfG+GavseY0Mq9Qfbz4uLvyetpRJLbCNfciE+WgetLMU27l/59yAqqoHg71B2ZCgocmm8ND8raqi+QfjRZazJIrimUvp3E3AtcdnWZ/6,iv:2xsVDOSEVXyGSlZwKvls10i6wM3dXa+0s+9AUZgGPxk=,tag:jEXCSFZlGR8CdRZquAVMAg==,type:str]
packages:
    db:
        DATABASE_URL: ENC[AES256_GCM,data:A0/YzZiB3hWzuYH2IZTbz9LYd0qZLRYGNJz9SQYi9NKML/1D5PoiL54JbTdH09Hk+Qvvwa273T0mInmP1cPWHV+/CxZB06S4nrcHOe9OlGUg,iv:OsIGhBACr4AcPgebBwjtM/nU1tQt/7oF9OYgVMM59Ek=,tag:xeNwzkSJS64cr1RHp0PXSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZEswNS9qMnRrMFlpUngx
            Y0hoNnZoT21uUHExVXJNREI2U0kyZmp4V1RVClRWYlZya3MxNWtjY3JoWjRmMUhZ
            N3ZIcE81ZTNENjhKQVJuRXQ4NXczOGcKLS0tIFZlNUNDSysvVzhKSEZvRld3RWgz
            L3pFN2ZmSk94TGM3bFh4YWlneEUrdmcKI3j9cmlZGWyf4rdG5s3+pycPzp9qXFMa
            m5M8uIqyuI5NQSStCpjvLVE3vdc0TN2+gI7jjvfdupgPVlicwd7T3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1pZWWtDZldFU2Izbkgy
            bnl5Z1hyOVptYWtDL0YyQXdQaTFPWUNLUXh3Ck44bzBQcng2TmlCZk5DRUhQNkxk
            eTJFS0FDYkd6Nk96M1Z3emZja3Y3c28KLS0tIGF4SHhXYk52bkZQRXcvN3ZNemtm
            elIzUER6cXBzY2J1MW5peDFyRVBpc3MKBKKzv4zjOjZ5qtAKYANdgk6yv9StI1Jh
            caxl6LNEaINmkqwyKpapKCRhmUOz6+JevieqF6JkNIRRyvuhltvoHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cgudsv52h62snquglvayft2n4ck522x4at5aja57un06w9w0gszqzfqtce
    lastmodified: "2026-09-09T11:46:15Z"
    mac: ENC[AES256_GCM,data:ZZ74WMvToltIj3i7ZQ57+BleIXElzEX4V3Mi4ahYs9bqD6jc7dFz+QO78D892qx2CB8AbMRC/Hnj1JvCganFYWkw9wAxsACZEFkuh72vSg3uASOeglsngPNiVeyWl8kuHpMrjbvwqFLB2mHZZo1oiFn6bdvNYix8UWvvByjit7k=,iv:tbO4z/MvoJdFvKDQCtHuQZNkJQAEbaUeV/tjE2Amkpg=,tag:4zgrhkyCdeKZ1AegUR4Mkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
